/**
 * StS1 铁甲战士(Ironclad) 卡牌数据
 * 完整收录：基础牌 + 普通 + 罕见 + 稀有
 */

export const ironcladCards = [
  // 基础牌
  { game_version: 'sts1', character: 'ironclad', name_cn: '打击', name_en: 'Strike', cost: 1, type: 'attack', rarity: 'basic', effect_base: '造成6点伤害。', effect_upgraded: '造成9点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '防御', name_en: 'Defend', cost: 1, type: 'skill', rarity: 'basic', effect_base: '获得5点格挡。', effect_upgraded: '获得8点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '痛击', name_en: 'Bash', cost: 2, type: 'attack', rarity: 'basic', effect_base: '造成8点伤害。给予2层易伤。', effect_upgraded: '造成10点伤害。给予3层易伤。', keywords: '["vulnerable"]' },
  // 普通攻击
  { game_version: 'sts1', character: 'ironclad', name_cn: '顺劈斩', name_en: 'Cleave', cost: 1, type: 'attack', rarity: 'common', effect_base: '对所有敌人造成8点伤害。', effect_upgraded: '对所有敌人造成11点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '上勾拳', name_en: 'Uppercut', cost: 2, type: 'attack', rarity: 'common', effect_base: '造成13点伤害。给予1层虚弱和1层易伤。', effect_upgraded: '造成13点伤害。给予2层虚弱和2层易伤。', keywords: '["vulnerable","weak"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '头槌', name_en: 'Headbutt', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成9点伤害。将弃牌堆中的一张牌放到抽牌堆顶部。', effect_upgraded: '造成12点伤害。将弃牌堆中的一张牌放到抽牌堆顶部。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '飞身踢', name_en: 'Clothesline', cost: 2, type: 'attack', rarity: 'common', effect_base: '造成12点伤害。给予2层虚弱。', effect_upgraded: '造成14点伤害。给予3层虚弱。', keywords: '["weak"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '重刃', name_en: 'Heavy Blade', cost: 2, type: 'attack', rarity: 'common', effect_base: '造成14点伤害。力量对其造成5倍伤害而非通常的加成。', effect_upgraded: '造成14点伤害。力量对其造成8倍伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '铁斩波', name_en: 'Iron Wave', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成5点伤害。获得5点格挡。', effect_upgraded: '造成7点伤害。获得7点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '完美打击', name_en: 'Perfected Strike', cost: 2, type: 'attack', rarity: 'common', effect_base: '造成18点伤害。你牌库中每有一张名字带"打击"的牌，伤害+2。', effect_upgraded: '造成18点伤害。你牌库中每有一张名字带"打击"的牌，伤害+3。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '剑柄打击', name_en: 'Pommel Strike', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成9点伤害。抽1张牌。', effect_upgraded: '造成10点伤害。抽2张牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '愤怒', name_en: 'Anger', cost: 0, type: 'attack', rarity: 'common', effect_base: '造成6点伤害。将这张牌的复制品放入弃牌堆。', effect_upgraded: '造成8点伤害。将这张牌的复制品放入弃牌堆。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '狂暴', name_en: 'Rampage', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成8点伤害。每次打出这张牌时，伤害+5。', effect_upgraded: '造成8点伤害。每次打出这张牌时，伤害+8。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '灵魂打击', name_en: 'Soul Strike', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成12点伤害。如果你在本回合斩杀敌人，永久获得+3最大生命。', effect_upgraded: '造成16点伤害。如果你在本回合斩杀敌人，永久获得+5最大生命。', keywords: '[]' },
  // 普通技能
  { game_version: 'sts1', character: 'ironclad', name_cn: '耸肩无视', name_en: 'Shrug It Off', cost: 1, type: 'skill', rarity: 'common', effect_base: '获得8点格挡。抽1张牌。', effect_upgraded: '获得11点格挡。抽1张牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '坚毅', name_en: 'True Grit', cost: 1, type: 'skill', rarity: 'common', effect_base: '获得7点格挡。消耗1张随机手牌。', effect_upgraded: '获得9点格挡。选择1张手牌消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '战斗专注', name_en: 'Battle Trance', cost: 0, type: 'skill', rarity: 'common', effect_base: '抽3张牌。你本回合不能再抽任何牌。', effect_upgraded: '抽4张牌。你本回合不能再抽任何牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '流血', name_en: 'Hemokinesis', cost: 1, type: 'skill', rarity: 'common', effect_base: '失去3点生命。造成15点伤害。', effect_upgraded: '失去2点生命。造成20点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '耸肩', name_en: 'Flex', cost: 0, type: 'skill', rarity: 'common', effect_base: '获得2点力量。在你的回合结束时，失去2点力量。', effect_upgraded: '获得4点力量。在你的回合结束时，失去4点力量。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '武装', name_en: 'Armaments', cost: 1, type: 'skill', rarity: 'common', effect_base: '获得5点格挡。将你手牌中所有可升级的牌升级。', effect_upgraded: '获得5点格挡。将你手牌中所有可升级的牌升级。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: ' thunderclap', name_en: 'Thunderclap', cost: 1, type: 'skill', rarity: 'common', effect_base: '对所有敌人造成4点伤害，并给予1层易伤。', effect_upgraded: '对所有敌人造成7点伤害，并给予1层易伤。', keywords: '["vulnerable"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '火焰吐息', name_en: 'Fire Breathing', cost: 1, type: 'power', rarity: 'common', effect_base: '每当你抽到一张状态牌时，对所有敌人造成6点伤害。', effect_upgraded: '每当你抽到一张状态牌时，对所有敌人造成10点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '发牌', name_en: 'Spot Weakness', cost: 1, type: 'skill', rarity: 'common', effect_base: '如果敌人意图攻击，给予3层易伤。', effect_upgraded: '如果敌人意图攻击，给予3层易伤。获得3点力量。', keywords: '["vulnerable"]' },
  // 罕见攻击
  { game_version: 'sts1', character: 'ironclad', name_cn: '旋风斩', name_en: 'Whirlwind', cost: -1, type: 'attack', rarity: 'uncommon', effect_base: '对所有敌人造成5点伤害X次。', effect_upgraded: '对所有敌人造成8点伤害X次。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '断魂斩', name_en: 'Searing Blow', cost: 2, type: 'attack', rarity: 'uncommon', effect_base: '造成12点伤害。每次升级这张牌，伤害+4和额外效果。', effect_upgraded: '造成12点伤害。每次升级这张牌，伤害+4。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '全身冲击', name_en: 'Body Slam', cost: 1, type: 'attack', rarity: 'uncommon', effect_base: '造成你当前格挡值的伤害。', effect_upgraded: '造成你当前格挡值的伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '禁言', name_en: 'Crippling Poison', cost: 2, type: 'attack', rarity: 'uncommon', effect_base: '造成8点伤害。给予敌人无法使用技能1回合。', effect_upgraded: '造成10点伤害。给予敌人无法使用技能2回合。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '掠夺', name_en: 'Pummel', cost: 1, type: 'attack', rarity: 'uncommon', effect_base: '造成2点伤害4次。', effect_upgraded: '造成2点伤害5次。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '幽灵打击', name_en: 'Reaper', cost: 2, type: 'attack', rarity: 'rare', effect_base: '对所有敌人造成4点伤害。未格挡的伤害为你恢复生命。消耗。', effect_upgraded: '对所有敌人造成5点伤害。未格挡的伤害为你恢复生命。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '残忍', name_en: 'Feed', cost: 1, type: 'attack', rarity: 'rare', effect_base: '造成10点伤害。如果你在本回合斩杀敌人，永久获得+3最大生命。消耗。', effect_upgraded: '造成12点伤害。如果你在本回合斩杀敌人，永久获得+4最大生命。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '恶魔形态', name_en: 'Demon Form', cost: 3, type: 'power', rarity: 'rare', effect_base: '在你的回合开始时，获得2点力量。', effect_upgraded: '在你的回合开始时，获得3点力量。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '双重打击', name_en: 'Twin Strike', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成5点伤害2次。', effect_upgraded: '造成7点伤害2次。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '狂野打击', name_en: 'Wild Strike', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成12点伤害。将一张伤口放入抽牌堆。', effect_upgraded: '造成17点伤害。将一张伤口放入抽牌堆。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '血祭', name_en: 'Offering', cost: 0, type: 'skill', rarity: 'rare', effect_base: '失去6点生命。获得2点能量。抽3张牌。消耗。', effect_upgraded: '失去6点生命。获得2点能量。抽5张牌。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '燃烧', name_en: 'Combust', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '在你的回合结束时，失去1点生命，对所有敌人造成5点伤害。', effect_upgraded: '在你的回合结束时，失去1点生命，对所有敌人造成7点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '黑暗之拥', name_en: 'Dark Embrace', cost: 2, type: 'power', rarity: 'rare', effect_base: '每当你消耗一张牌时，抽1张牌。', effect_upgraded: '每当你消耗一张牌时，抽1张牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '进化', name_en: 'Evolve', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '每当你抽到一张伤口牌时，抽1张牌。', effect_upgraded: '每当你抽到一张伤口牌时，抽2张牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '火焰屏障', name_en: 'Flame Barrier', cost: 2, type: 'skill', rarity: 'uncommon', effect_base: '获得12点格挡。你本回合每被攻击一次，对攻击者造成4点伤害。', effect_upgraded: '获得16点格挡。你本回合每被攻击一次，对攻击者造成6点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '金属化', name_en: 'Metallicize', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '在你的回合结束时，获得3点格挡。', effect_upgraded: '在你的回合结束时，获得4点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '撕裂', name_en: 'Rupture', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '每当你失去生命时，获得1点力量。', effect_upgraded: '每当你失去生命时，获得2点力量。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '耸肩无视', name_en: 'Seeing Red', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '获得2点能量。消耗。', effect_upgraded: '获得2点能量。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '震荡波', name_en: 'Shockwave', cost: 2, type: 'skill', rarity: 'uncommon', effect_base: '给予所有敌人3层虚弱和3层易伤。消耗。', effect_upgraded: '给予所有敌人5层虚弱和5层易伤。消耗。', keywords: '["exhaust","vulnerable","weak"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: '缴械', name_en: 'Disarm', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '敌人失去2点力量。消耗。', effect_upgraded: '敌人失去3点力量。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: ' Entrench', name_en: 'Entrench', cost: 2, type: 'skill', rarity: 'uncommon', effect_base: '将你的格挡翻倍。', effect_upgraded: '将你的格挡翻倍。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Ghostly Armor', name_en: 'Ghostly Armor', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '获得10点格挡。消耗。', effect_upgraded: '获得13点格挡。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Limit Break', name_en: 'Limit Break', cost: 1, type: 'skill', rarity: 'rare', effect_base: '将你的力量翻倍。消耗。', effect_upgraded: '将你的力量翻倍。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Impervious', name_en: 'Impervious', cost: 2, type: 'skill', rarity: 'rare', effect_base: '获得30点格挡。消耗。', effect_upgraded: '获得40点格挡。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Juggernaut', name_en: 'Juggernaut', cost: 2, type: 'power', rarity: 'rare', effect_base: '每当你获得格挡时，对随机敌人造成5点伤害。', effect_upgraded: '每当你获得格挡时，对随机敌人造成7点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Barricade', name_en: 'Barricade', cost: 3, type: 'power', rarity: 'rare', effect_base: '格挡不会在回合开始时消失。', effect_upgraded: '格挡不会在回合开始时消失。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Berserk', name_en: 'Berserk', cost: 0, type: 'power', rarity: 'rare', effect_base: '获得2层易伤。在你的回合开始时，获得1点能量。', effect_upgraded: '获得2层易伤。在你的回合开始时，获得2点能量。', keywords: '["vulnerable"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Brutality', name_en: 'Brutality', cost: 0, type: 'power', rarity: 'rare', effect_base: '在你的回合开始时，失去1点生命，抽1张牌。', effect_upgraded: '在你的回合开始时，失去1点生命，抽2张牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Corruption', name_en: 'Corruption', cost: 3, type: 'power', rarity: 'rare', effect_base: '所有技能牌变为消耗牌。每当你消耗一张技能牌时，获得2点能量。', effect_upgraded: '所有技能牌变为消耗牌。每当你消耗一张技能牌时，获得2点能量。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Exhume', name_en: 'Exhume', cost: 1, type: 'skill', rarity: 'rare', effect_base: '将消耗牌堆中的一张牌放入你的手牌。消耗。', effect_upgraded: '将消耗牌堆中的一张牌放入你的手牌。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Fiend Fire', name_en: 'Fiend Fire', cost: 2, type: 'attack', rarity: 'rare', effect_base: '消耗所有手牌。每张被消耗的牌造成7点伤害。消耗。', effect_upgraded: '消耗所有手牌。每张被消耗的牌造成10点伤害。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Immolate', name_en: 'Immolate', cost: 2, type: 'attack', rarity: 'rare', effect_base: '对所有敌人造成21点伤害。将一张烧伤放入弃牌堆。', effect_upgraded: '对所有敌人造成28点伤害。将一张烧伤放入弃牌堆。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Sentinel', name_en: 'Sentinel', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '获得5点格挡。如果这张牌被消耗，获得3点能量。', effect_upgraded: '获得8点格挡。如果这张牌被消耗，获得4点能量。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Double Tap', name_en: 'Double Tap', cost: 1, type: 'skill', rarity: 'rare', effect_base: '本回合你的下一张攻击牌将被打出两次。', effect_upgraded: '本回合你的下两张攻击牌将被打出两次。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Dropkick', name_en: 'Dropkick', cost: 1, type: 'attack', rarity: 'uncommon', effect_base: '造成5点伤害。如果敌人有易伤，获得1点能量并抽1张牌。', effect_upgraded: '造成8点伤害。如果敌人有易伤，获得1点能量并抽1张牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Feel No Pain', name_en: 'Feel No Pain', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '每当你消耗一张牌时，获得3点格挡。', effect_upgraded: '每当你消耗一张牌时，获得4点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Inflame', name_en: 'Inflame', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '获得2点力量。', effect_upgraded: '获得3点力量。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Intimidate', name_en: 'Intimidate', cost: 0, type: 'skill', rarity: 'uncommon', effect_base: '给予所有敌人1层虚弱。消耗。', effect_upgraded: '给予所有敌人2层虚弱。消耗。', keywords: '["exhaust","weak"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Power Through', name_en: 'Power Through', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '增加2张伤口到你的手牌。获得15点格挡。', effect_upgraded: '增加2张伤口到你的手牌。获得20点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Second Wind', name_en: 'Second Wind', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '消耗所有非攻击手牌。每张被消耗的牌获得5点格挡。', effect_upgraded: '消耗所有非攻击手牌。每张被消耗的牌获得7点格挡。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'ironclad', name_cn: 'Sever Soul', name_en: 'Sever Soul', cost: 2, type: 'attack', rarity: 'uncommon', effect_base: '消耗所有非攻击手牌。每张被消耗的牌造成16点伤害。', effect_upgraded: '消耗所有非攻击手牌。每张被消耗的牌造成22点伤害。', keywords: '["exhaust"]' },
];
