/**
 * StS1 故障机器人(Defect) 卡牌数据
 * 收录核心卡牌
 */

export const defectCards = [
  // 基础牌
  { game_version: 'sts1', character: 'defect', name_cn: '打击', name_en: 'Strike', cost: 1, type: 'attack', rarity: 'basic', effect_base: '造成6点伤害。', effect_upgraded: '造成9点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '防御', name_en: 'Defend', cost: 1, type: 'skill', rarity: 'basic', effect_base: '获得5点格挡。', effect_upgraded: '获得8点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '双发', name_en: 'Dualcast', cost: 0, type: 'skill', rarity: 'basic', effect_base: '激发你下一个充能球的效果2次。消耗。', effect_upgraded: '激发你下一个充能球的效果2次。消耗。', keywords: '["exhaust","evoke"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '齐射', name_en: 'Zap', cost: 1, type: 'skill', rarity: 'basic', effect_base: '生成1个闪电充能球。', effect_upgraded: '生成1个闪电充能球。', keywords: '["orb"]' },
  // 普通攻击
  { game_version: 'sts1', character: 'defect', name_cn: '球状闪电', name_en: 'Ball Lightning', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成7点伤害。生成1个闪电充能球。', effect_upgraded: '造成10点伤害。生成1个闪电充能球。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' cold snap', name_en: 'Cold Snap', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成6点伤害。生成1个冰霜充能球。', effect_upgraded: '造成9点伤害。生成1个冰霜充能球。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '精简改良', name_en: 'Streamline', cost: 2, type: 'attack', rarity: 'common', effect_base: '造成15点伤害。每次打出这张牌时，费用减少1点直到本回合结束。', effect_upgraded: '造成20点伤害。每次打出这张牌时，费用减少1点直到本回合结束。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '超光速', name_en: 'Charge Beam', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成3点伤害。你手牌中每有一张充能球生成牌，伤害+3。', effect_upgraded: '造成3点伤害。你手牌中每有一张充能球生成牌，伤害+4。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '扫荡射线', name_en: 'Sweeping Beam', cost: 1, type: 'attack', rarity: 'common', effect_base: '对所有敌人造成6点伤害。抽1张牌。', effect_upgraded: '对所有敌人造成9点伤害。抽1张牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '熔化', name_en: 'Melter', cost: 1, type: 'attack', rarity: 'uncommon', effect_base: '造成10点伤害。移除敌人的所有格挡。', effect_upgraded: '造成10点伤害。移除敌人的所有格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '全息影像', name_en: 'Rip and Tear', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成7点伤害2次。', effect_upgraded: '造成9点伤害2次。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' Blizzard', name_en: 'Blizzard', cost: 1, type: 'attack', rarity: 'uncommon', effect_base: '对所有敌人造成你当前充能球总数2倍的伤害。', effect_upgraded: '对所有敌人造成你当前充能球总数2倍的伤害。这场战斗中，所有敌人受到的伤害+2。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' doom and gloom', name_en: 'Doom and Gloom', cost: 2, type: 'attack', rarity: 'uncommon', effect_base: '对所有敌人造成10点伤害。生成1个黑暗充能球。', effect_upgraded: '对所有敌人造成14点伤害。生成1个黑暗充能球。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' hyperbeam', name_en: 'Hyperbeam', cost: 2, type: 'attack', rarity: 'rare', effect_base: '对所有敌人造成26点伤害。失去3点集中力。', effect_upgraded: '对所有敌人造成34点伤害。失去3点集中力。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' thunder strike', name_en: 'Thunder Strike', cost: 3, type: 'attack', rarity: 'rare', effect_base: '造成7点伤害X次，X为这场战斗你激发的闪电球数量。', effect_upgraded: '造成9点伤害X次，X为这场战斗你激发的闪电球数量。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' all for one', name_en: 'All for One', cost: 2, type: 'attack', rarity: 'rare', effect_base: '造成10点伤害。将弃牌堆中所有费用为0的牌加入手牌。', effect_upgraded: '造成14点伤害。将弃牌堆中所有费用为0的牌加入手牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' claw', name_en: 'Claw', cost: 0, type: 'attack', rarity: 'common', effect_base: '造成3点伤害。本场战斗中所有Claw伤害+2。', effect_upgraded: '造成5点伤害。本场战斗中所有Claw伤害+2。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' go for the eyes', name_en: 'Go for the Eyes', cost: 0, type: 'attack', rarity: 'common', effect_base: '造成3点伤害。如果敌人意图攻击，给予1层虚弱。', effect_upgraded: '造成4点伤害。如果敌人意图攻击，给予2层虚弱。', keywords: '["weak"]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' rebound', name_en: 'Rebound', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成9点伤害。将你下一张打出的牌放到抽牌堆顶部。', effect_upgraded: '造成12点伤害。将你下一张打出的牌放到抽牌堆顶部。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' rip and tear', name_en: 'Rip and Tear', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成7点伤害2次。', effect_upgraded: '造成9点伤害2次。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' scour', name_en: 'Scrape', cost: 1, type: 'attack', rarity: 'uncommon', effect_base: '造成7点伤害。抽3张牌。丢弃抽到费用为0的牌。', effect_upgraded: '造成10点伤害。抽4张牌。丢弃抽到费用为0的牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' sunder', name_en: 'Sunder', cost: 3, type: 'attack', rarity: 'uncommon', effect_base: '造成24点伤害。如果斩杀敌人，获得3点能量。', effect_upgraded: '造成32点伤害。如果斩杀敌人，获得3点能量。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' beam cell', name_en: 'Beam Cell', cost: 0, type: 'attack', rarity: 'common', effect_base: '造成3点伤害。给予1层脆弱。', effect_upgraded: '造成4点伤害。给予2层脆弱。', keywords: '["vulnerable"]' },
  // 普通技能
  { game_version: 'sts1', character: 'defect', name_cn: '冰寒', name_en: 'Coolheaded', cost: 1, type: 'skill', rarity: 'common', effect_base: '生成1个冰霜充能球。抽1张牌。', effect_upgraded: '生成1个冰霜充能球。抽2张牌。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '充电', name_en: 'Charge Battery', cost: 1, type: 'skill', rarity: 'common', effect_base: '生成1个冰霜充能球。获得7点格挡。', effect_upgraded: '生成1个冰霜充能球。获得10点格挡。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '跃迁', name_en: 'Leap', cost: 1, type: 'skill', rarity: 'common', effect_base: '获得9点格挡。', effect_upgraded: '获得12点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '编译冲击', name_en: 'Compile Driver', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成7点伤害。你手牌中每有一种不同的充能球类型，伤害+7。', effect_upgraded: '造成10点伤害。你手牌中每有一种不同的充能球类型，伤害+7。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '缓冲', name_en: 'Stack', cost: 1, type: 'skill', rarity: 'common', effect_base: '获得等同弃牌堆数量的格挡。', effect_upgraded: '获得等同弃牌堆数量+3的格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '蒸汽护壁', name_en: 'Steam Barrier', cost: 0, type: 'skill', rarity: 'common', effect_base: '获得6点格挡。每打出一次本回合减少1点格挡。', effect_upgraded: '获得8点格挡。每打出一次本回合减少1点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '涡轮增压', name_en: 'Turbo', cost: 0, type: 'skill', rarity: 'common', effect_base: '获得3点能量。增加2张虚空到抽牌堆。', effect_upgraded: '获得3点能量。增加1张虚空到抽牌堆。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '混沌', name_en: 'Chaos', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '生成1个随机充能球。', effect_upgraded: '生成1个随机充能球。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '聚合', name_en: 'Conserve Battery', cost: 2, type: 'skill', rarity: 'uncommon', effect_base: '生成1个冰霜充能球。获得7点格挡。下回合开始时获得1点能量。', effect_upgraded: '生成1个冰霜充能球。获得9点格挡。下回合开始时获得1点能量。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '暗黑之握', name_en: 'Darkness', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '生成1个黑暗充能球。', effect_upgraded: '生成1个黑暗充能球。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '双重释放', name_en: 'Double Energy', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '将你的能量翻倍。消耗。', effect_upgraded: '将你的能量翻倍。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '折跃', name_en: 'Fission', cost: 0, type: 'skill', rarity: 'rare', effect_base: '激发所有充能球。每激发一个，抽1张牌并获得1点能量。', effect_upgraded: '激发所有充能球。每激发一个，抽1张牌并获得1点能量。', keywords: '["evoke"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '力场', name_en: 'Force Field', cost: 4, type: 'skill', rarity: 'uncommon', effect_base: '获得12点格挡。你手牌中每有一张能力牌，费用减少1点。', effect_upgraded: '获得12点格挡。你手牌中每有一张能力牌，费用减少1点。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '遗传算法', name_en: 'Genetic Algorithm', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '获得1点格挡。每当你打出这张牌时，格挡+1。消耗。', effect_upgraded: '获得1点格挡。每当你打出这张牌时，格挡+2。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '冰川', name_en: 'Glacier', cost: 2, type: 'skill', rarity: 'uncommon', effect_base: '生成2个冰霜充能球。获得5点格挡。', effect_upgraded: '生成2个冰霜充能球。获得7点格挡。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '递归', name_en: 'Recursion', cost: 1, type: 'skill', rarity: 'common', effect_base: '激发你最右侧的充能球。然后将下一个充能球放到最右侧。', effect_upgraded: '激发你最右侧的充能球。然后将下一个充能球放到最右侧。', keywords: '["evoke"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '重组', name_en: 'Recycle', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '消耗1张手牌。获得等同其费用的能量。', effect_upgraded: '消耗1张手牌。获得等同其费用+2的能量。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '重编程', name_en: 'Reprogram', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '失去1点集中力。获得1点力量和1点敏捷。', effect_upgraded: '失去1点集中力。获得2点力量和2点敏捷。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '碎片整理', name_en: 'Defragment', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '获得1点集中力。', effect_upgraded: '获得2点集中力。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '碎片风暴', name_en: 'Aggregate', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '获得等同你当前充能球数量2倍的格挡。', effect_upgraded: '获得等同你当前充能球数量3倍的格挡。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '扩容', name_en: 'Capacitor', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '获得2个充能球栏位。', effect_upgraded: '获得3个充能球栏位。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '耗尽', name_en: 'Consume', cost: 2, type: 'skill', rarity: 'uncommon', effect_base: '激发你最右侧的充能球。获得2点集中力。失去1个充能球栏位。', effect_upgraded: '激发你最右侧的充能球。获得3点集中力。失去1个充能球栏位。', keywords: '["evoke"]' },
  { game_version: 'sts1', character: 'defect', name_cn: ' hello world', name_en: 'Hello World', cost: 1, type: 'power', rarity: 'common', effect_base: '在你的回合开始时，增加1张随机普通无色攻击牌到你的手牌。', effect_upgraded: '在你的回合开始时，增加1张随机普通无色攻击牌到你的手牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '内核加速', name_en: 'Core Surge', cost: 1, type: 'attack', rarity: 'rare', effect_base: '造成11点伤害。获得1个充能球。获得1层人工制品。消耗。', effect_upgraded: '造成15点伤害。获得1个充能球。获得1层人工制品。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '创造性AI', name_en: 'Creative AI', cost: 3, type: 'power', rarity: 'rare', effect_base: '在你的回合开始时，增加1张随机能力牌到你的手牌。', effect_upgraded: '在你的回合开始时，增加1张随机能力牌到你的手牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: '电动力学', name_en: 'Electrodynamics', cost: 2, type: 'power', rarity: 'rare', effect_base: '在你的回合开始时，生成1个闪电充能球。你的闪电球现在攻击所有敌人。', effect_upgraded: '在你的回合开始时，生成2个闪电充能球。你的闪电球现在攻击所有敌人。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: '偏差认知', name_en: 'Biased Cognition', cost: 1, type: 'power', rarity: 'rare', effect_base: '获得4点集中力。在你的回合开始时，失去1点集中力。', effect_upgraded: '获得5点集中力。在你的回合开始时，失去1点集中力。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: 'Machine Learning', name_en: 'Machine Learning', cost: 1, type: 'power', rarity: 'rare', effect_base: '在你的回合开始时，抽1张额外的牌。', effect_upgraded: '在你的回合开始时，抽1张额外的牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: 'Static Discharge', name_en: 'Static Discharge', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '每当你受到攻击伤害时，生成1个闪电充能球。', effect_upgraded: '每当你受到攻击伤害时，生成2个闪电充能球。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: 'Storm', name_en: 'Storm', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '每当你打出一张充能球生成牌时，生成1个闪电充能球。', effect_upgraded: '每当你打出一张充能球生成牌时，生成2个闪电充能球。', keywords: '["orb"]' },
  { game_version: 'sts1', character: 'defect', name_cn: 'Self Repair', name_en: 'Self Repair', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '在你的回合结束时，恢复3点生命。', effect_upgraded: '在你的回合结束时，恢复5点生命。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: 'Loop', name_en: 'Loop', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '在你的回合开始时，激发你最右侧的充能球。', effect_upgraded: '在你的回合开始时，激发你最右侧的充能球两次。', keywords: '["evoke"]' },
  { game_version: 'sts1', character: 'defect', name_cn: 'Amplify', name_en: 'Amplify', cost: 1, type: 'skill', rarity: 'rare', effect_base: '本回合你的下一张能力牌打出两次。', effect_upgraded: '本回合你的下一张能力牌打出两次。', keywords: '[]' },
  { game_version: 'sts1', character: 'defect', name_cn: 'Rainbow', name_en: 'Rainbow', cost: 2, type: 'skill', rarity: 'rare', effect_base: '生成1个闪电、冰霜和黑暗充能球。消耗。', effect_upgraded: '生成1个闪电、冰霜和黑暗充能球。', keywords: '["exhaust","orb"]' },
];
