/**
 * StS1 静默猎手(Silent) 卡牌数据
 * 收录核心卡牌：基础 + 常见攻击/技能/能力
 */

export const silentCards = [
  // 基础牌
  { game_version: 'sts1', character: 'silent', name_cn: '打击', name_en: 'Strike', cost: 1, type: 'attack', rarity: 'basic', effect_base: '造成6点伤害。', effect_upgraded: '造成9点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: '防御', name_en: 'Defend', cost: 1, type: 'skill', rarity: 'basic', effect_base: '获得5点格挡。', effect_upgraded: '获得8点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: '幸存', name_en: 'Survivor', cost: 1, type: 'skill', rarity: 'basic', effect_base: '获得8点格挡。丢弃1张手牌。', effect_upgraded: '获得11点格挡。丢弃1张手牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: '中和', name_en: 'Neutralize', cost: 0, type: 'attack', rarity: 'basic', effect_base: '造成3点伤害。给予1层虚弱。', effect_upgraded: '造成4点伤害。给予2层虚弱。', keywords: '["weak"]' },
  // 普通攻击
  { game_version: 'sts1', character: 'silent', name_cn: '匕首投掷', name_en: 'Dagger Throw', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成9点伤害。抽1张牌。丢弃1张手牌。', effect_upgraded: '造成12点伤害。抽1张牌。丢弃1张手牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: '快斩', name_en: 'Quick Slash', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成8点伤害。抽1张牌。', effect_upgraded: '造成12点伤害。抽1张牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: '侧翼打击', name_en: 'Sucker Punch', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成7点伤害。给予1层虚弱。', effect_upgraded: '造成9点伤害。给予2层虚弱。', keywords: '["weak"]' },
  { game_version: 'sts1', character: 'silent', name_cn: '背刺', name_en: 'Backstab', cost: 0, type: 'attack', rarity: 'uncommon', effect_base: '造成11点伤害。消耗。', effect_upgraded: '造成15点伤害。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'silent', name_cn: '窒息', name_en: 'Choke', cost: 2, type: 'attack', rarity: 'uncommon', effect_base: '造成12点伤害。本回合每打出一张牌，给予敌人3层窒息。', effect_upgraded: '造成12点伤害。本回合每打出一张牌，给予敌人5层窒息。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: '匕首雨', name_en: 'Dagger Spray', cost: 1, type: 'attack', rarity: 'common', effect_base: '对所有敌人造成4点伤害2次。', effect_upgraded: '对所有敌人造成6点伤害2次。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: '涂毒', name_en: 'Poisoned Stab', cost: 1, type: 'attack', rarity: 'common', effect_base: '造成6点伤害。给予3层中毒。', effect_upgraded: '造成8点伤害。给予4层中毒。', keywords: '["poison"]' },
  { game_version: 'sts1', character: 'silent', name_cn: '终结技', name_en: 'Finisher', cost: 1, type: 'attack', rarity: 'uncommon', effect_base: '本回合每打出一张攻击牌，造成6点伤害。', effect_upgraded: '本回合每打出一张攻击牌，造成8点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' Flechettes', name_en: 'Flechettes', cost: 1, type: 'attack', rarity: 'uncommon', effect_base: '你手牌中每有一张技能牌，造成4点伤害。', effect_upgraded: '你手牌中每有一张技能牌，造成6点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' heel hook', name_en: 'Heel Hook', cost: 1, type: 'attack', rarity: 'uncommon', effect_base: '造成5点伤害。如果敌人有虚弱，获得1点能量并抽1张牌。', effect_upgraded: '造成8点伤害。如果敌人有虚弱，获得1点能量并抽1张牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: '千刃', name_en: 'Thousand Cuts', cost: 2, type: 'power', rarity: 'rare', effect_base: '每当你打出一张牌时，对所有敌人造成1点伤害。', effect_upgraded: '每当你打出一张牌时，对所有敌人造成2点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: '玻璃刀', name_en: 'Glass Knife', cost: 1, type: 'attack', rarity: 'rare', effect_base: '造成8点伤害2次。每当打出一张Glass Knife，本回合Glass Knife的伤害-2。', effect_upgraded: '造成8点伤害2次。每当打出一张Glass Knife，本回合Glass Knife的伤害-1。', keywords: '[]' },
  // 普通技能
  { game_version: 'sts1', character: 'silent', name_cn: '足跟勾', name_en: 'Leg Sweep', cost: 2, type: 'skill', rarity: 'common', effect_base: '给予2层虚弱。获得12点格挡。', effect_upgraded: '给予3层虚弱。获得15点格挡。', keywords: '["weak"]' },
  { game_version: 'sts1', character: 'silent', name_cn: '闪避翻滚', name_en: 'Dodge and Roll', cost: 1, type: 'skill', rarity: 'common', effect_base: '获得4点格挡。下回合获得4点格挡。', effect_upgraded: '获得6点格挡。下回合获得6点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: '刺击', name_en: 'Piercing Wail', cost: 1, type: 'skill', rarity: 'common', effect_base: '给予所有敌人6层虚弱。消耗。', effect_upgraded: '给予所有敌人8层虚弱。消耗。', keywords: '["exhaust","weak"]' },
  { game_version: 'sts1', character: 'silent', name_cn: '准备', name_en: 'Prepared', cost: 0, type: 'skill', rarity: 'common', effect_base: '抽1张牌。丢弃1张手牌。', effect_upgraded: '抽2张牌。丢弃2张手牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: 'Blur', name_en: 'Blur', cost: 1, type: 'skill', rarity: 'common', effect_base: '获得5点格挡。格挡不会在下回合开始时被移除。', effect_upgraded: '获得8点格挡。格挡不会在下回合开始时被移除。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' Catalyst', name_en: 'Catalyst', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '将敌人的中毒层数翻倍。消耗。', effect_upgraded: '将敌人的中毒层数变为3倍。消耗。', keywords: '["exhaust","poison"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' corpse explosion', name_en: 'Corpse Explosion', cost: 2, type: 'skill', rarity: 'rare', effect_base: '给予9层中毒。当敌人死亡时，对所有敌人造成等于其最大生命值的伤害。', effect_upgraded: '给予9层中毒。当敌人死亡时，对所有敌人造成等于其最大生命值的伤害。', keywords: '["poison"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' crippling cloud', name_en: 'Crippling Cloud', cost: 2, type: 'skill', rarity: 'uncommon', effect_base: '给予所有敌人4层中毒和2层虚弱。消耗。', effect_upgraded: '给予所有敌人6层中毒和2层虚弱。消耗。', keywords: '["exhaust","poison","weak"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' deadly poison', name_en: 'Deadly Poison', cost: 1, type: 'skill', rarity: 'common', effect_base: '给予5层中毒。', effect_upgraded: '给予7层中毒。', keywords: '["poison"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' deflect', name_en: 'Deflect', cost: 0, type: 'skill', rarity: 'common', effect_base: '获得4点格挡。', effect_upgraded: '获得7点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' dash', name_en: 'Dash', cost: 2, type: 'attack', rarity: 'uncommon', effect_base: '造成10点伤害。获得10点格挡。', effect_upgraded: '造成13点伤害。获得13点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' distraction', name_en: 'Distraction', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '增加1张随机无色技能牌到你的手牌。消耗。', effect_upgraded: '增加1张随机无色技能牌到你的手牌。它本回合费用为0。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' acrobatics', name_en: 'Acrobatics', cost: 1, type: 'skill', rarity: 'common', effect_base: '抽3张牌。丢弃1张手牌。', effect_upgraded: '抽4张牌。丢弃1张手牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' adrenaline', name_en: 'Adrenaline', cost: 0, type: 'skill', rarity: 'rare', effect_base: '获得2点能量。抽2张牌。消耗。', effect_upgraded: '获得2点能量。抽2张牌。抽取的牌本回合费用为0。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' alchemize', name_en: 'Alchemize', cost: 1, type: 'skill', rarity: 'rare', effect_base: '获得1张随机药水。消耗。', effect_upgraded: '获得1张随机药水。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' bullet time', name_en: 'Bullet Time', cost: 3, type: 'skill', rarity: 'rare', effect_base: '你本回合无法抽牌。你手牌中所有牌的当前费用变为0。', effect_upgraded: '你本回合无法抽牌。你手牌中所有牌的当前费用变为0。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' burst', name_en: 'Burst', cost: 1, type: 'skill', rarity: 'rare', effect_base: '本回合你的下一张技能牌将打出两次。', effect_upgraded: '本回合你的下两张技能牌将打出两次。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' concentration', name_en: 'Concentrate', cost: 0, type: 'skill', rarity: 'uncommon', effect_base: '丢弃3张手牌。获得2点能量。', effect_upgraded: '丢弃2张手牌。获得2点能量。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' crippling poison', name_en: 'Crippling Poison', cost: 2, type: 'skill', rarity: 'uncommon', effect_base: '给予所有敌人4层中毒和2层虚弱。消耗。', effect_upgraded: '给予所有敌人6层中毒和2层虚弱。消耗。', keywords: '["exhaust","poison","weak"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' endless agony', name_en: 'Endless Agony', cost: 0, type: 'attack', rarity: 'uncommon', effect_base: '造成4点伤害2次。将这张牌的复制品放入弃牌堆。', effect_upgraded: '造成5点伤害2次。将这张牌的复制品放入弃牌堆。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' escape plan', name_en: 'Escape Plan', cost: 0, type: 'skill', rarity: 'uncommon', effect_base: '抽1张牌。如果抽到的是技能牌，获得5点格挡。', effect_upgraded: '抽1张牌。如果抽到的是技能牌，获得7点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' eviscerate', name_en: 'Eviscerate', cost: 3, type: 'attack', rarity: 'uncommon', effect_base: '造成7点伤害3次。你每丢弃一张牌，费用-1。', effect_upgraded: '造成9点伤害3次。你每丢弃一张牌，费用-1。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' expertise', name_en: 'Expertise', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '抽牌直到手牌有6张。', effect_upgraded: '抽牌直到手牌有6张。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' footwork', name_en: 'Footwork', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '获得2点敏捷。', effect_upgraded: '获得3点敏捷。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' accuracy', name_en: 'Accuracy', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '小刀伤害+4。', effect_upgraded: '小刀伤害+6。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' after image', name_en: 'After Image', cost: 1, type: 'power', rarity: 'rare', effect_base: '每当你打出一张牌时，获得1点格挡。', effect_upgraded: '每当你打出一张牌时，获得1点格挡。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' alch fire', name_en: 'Alchemic Fire', cost: 1, type: 'skill', rarity: 'uncommon', effect_base: '获得1张随机药水。消耗。', effect_upgraded: '获得1张随机药水。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' bouncing flask', name_en: 'Bouncing Flask', cost: 2, type: 'skill', rarity: 'uncommon', effect_base: '给予3层中毒3次。', effect_upgraded: '给予3层中毒4次。', keywords: '["poison"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' calculated gamble', name_en: 'Calculated Gamble', cost: 0, type: 'skill', rarity: 'uncommon', effect_base: '丢弃所有手牌。抽同等数量的牌。消耗。', effect_upgraded: '丢弃所有手牌。抽同等数量的牌。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' grand finale', name_en: 'Grand Finale', cost: 0, type: 'attack', rarity: 'rare', effect_base: '只有当抽牌堆为空时才能打出。造成50点伤害。', effect_upgraded: '只有当抽牌堆为空时才能打出。造成60点伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' malaise', name_en: 'Malaise', cost: -1, type: 'skill', rarity: 'rare', effect_base: '给予敌人X层虚弱。移除敌人X点力量。消耗。', effect_upgraded: '给予敌人X+1层虚弱。移除敌人X+1点力量。消耗。', keywords: '["exhaust","weak"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' nightmare', name_en: 'Nightmare', cost: 3, type: 'skill', rarity: 'rare', effect_base: '选择一张手牌。下回合开始时，将3张复制品加入手牌。消耗。', effect_upgraded: '选择一张手牌。下回合开始时，将3张复制品加入手牌。消耗。', keywords: '["exhaust"]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' phantasmal killer', name_en: 'Phantasmal Killer', cost: 1, type: 'skill', rarity: 'rare', effect_base: '下回合你的攻击造成双倍伤害。', effect_upgraded: '下回合你的攻击造成双倍伤害。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' storm of steel', name_en: 'Storm of Steel', cost: 1, type: 'skill', rarity: 'rare', effect_base: '将你手牌中每张牌替换为1张小刀。丢弃的手牌每张额外增加1张小刀。', effect_upgraded: '将你手牌中每张牌替换为1张小刀。丢弃的手牌每张额外增加1张小刀。打出的小刀本回合伤害+4。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' tools of the trade', name_en: 'Tools of the Trade', cost: 1, type: 'power', rarity: 'rare', effect_base: '在你的回合开始时，抽1张牌并丢弃1张手牌。', effect_upgraded: '在你的回合开始时，抽1张牌并丢弃1张手牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' well laid plans', name_en: 'Well-Laid Plans', cost: 0, type: 'power', rarity: 'uncommon', effect_base: '在你的回合结束时，保留最多1张手牌。', effect_upgraded: '在你的回合结束时，保留最多2张手牌。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' wraith form', name_en: 'Wraith Form', cost: 3, type: 'power', rarity: 'rare', effect_base: '获得3层幽灵形态。在你的回合开始时，失去1点敏捷。', effect_upgraded: '获得3层幽灵形态。在你的回合开始时，失去1点敏捷。', keywords: '[]' },
  { game_version: 'sts1', character: 'silent', name_cn: ' noxious fumes', name_en: 'Noxious Fumes', cost: 1, type: 'power', rarity: 'uncommon', effect_base: '在你的回合开始时，给予所有敌人2层中毒。', effect_upgraded: '在你的回合开始时，给予所有敌人3层中毒。', keywords: '["poison"]' },
];
