/**
 * StS1 敌人/BOSS数据
 */

export const enemiesData = [
  // Act 1 普通敌人
  { game_version: 'sts1', name_cn: '虱虫', name_en: 'Louse', act: 1, type: 'normal', hp_min: 10, hp_max: 15, intents: '[{"pattern":"攻击","damage":5,"condition":"50%概率"},{"pattern":"防御","block":6,"condition":"50%概率"}]', strategy_general: '小虫威胁不大，优先处理。', strategy_by_character: '{"ironclad":"正常输出","silent":"中毒有效","defect":"充能球即可","watcher":"正常输出"}' },
  { game_version: 'sts1', name_cn: '酸液史莱姆', name_en: 'Acid Slime', act: 1, type: 'normal', hp_min: 20, hp_max: 25, intents: '[{"pattern":"攻击","damage":8},{"pattern":"虚弱攻击","damage":5,"buff":"虚弱"}]', strategy_general: '分裂前尽量多输出。', strategy_by_character: '{"ironclad":"力量牌有效","silent":"毒对分裂体有效","defect":"AOE处理分裂体","watcher":"姿态切换快速清场"}' },
  { game_version: 'sts1', name_cn: '尖刺史莱姆', name_en: 'Spike Slime', act: 1, type: 'normal', hp_min: 15, hp_max: 20, intents: '[{"pattern":"攻击","damage":10},{"pattern":"防御","block":10}]', strategy_general: '注意尖刺反伤，用格挡应对。', strategy_by_character: '{"ironclad":"格挡后反击","silent":"毒避开尖刺","defect":"闪电球远程","watcher":"平静姿态格挡"}' },
  { game_version: 'sts1', name_cn: '狱卒', name_en: 'Jaw Worm', act: 1, type: 'normal', hp_min: 40, hp_max: 44, intents: '[{"pattern":"攻击+格挡","damage":11,"block":5},{"pattern":"强化","buff":"力量+3"}]', strategy_general: '尽早击杀，不要让它叠力量。', strategy_by_character: '{"ironclad":"爆发输出","silent":"毒慢慢磨","defect":"闪电球持续输出","watcher":"愤怒姿态爆发"}' },
  { game_version: 'sts1', name_cn: '红虱', name_en: 'Red Louse', act: 1, type: 'normal', hp_min: 10, hp_max: 15, intents: '[{"pattern":"攻击","damage":5,"condition":"攻击或格挡"}]', strategy_general: '快速击杀即可。', strategy_by_character: null },
  { game_version: 'sts1', name_cn: '绿虱', name_en: 'Green Louse', act: 1, type: 'normal', hp_min: 10, hp_max: 15, intents: '[{"pattern":"攻击+格挡","damage":5,"block":6}]', strategy_general: '快速击杀即可。', strategy_by_character: null },
  // Act 1 精英
  { game_version: 'sts1', name_cn: '地精大块头', name_en: 'Gremlin Nob', act: 1, type: 'elite', hp_min: 82, hp_max: 86, intents: '[{"pattern":"攻击","damage":14},{"pattern":"狂暴","buff":"力量+2"}]', strategy_general: '出牌要快，每出一张技能牌它都会+3力量。尽量用攻击牌。', strategy_by_character: '{"ironclad":"攻击为主，少出技能","silent":"很难打，尽量 poison","defect":"攻击充能球，避免技能","watcher":"愤怒姿态攻击"}' },
  { game_version: 'sts1', name_cn: ' lagavulin', name_en: 'Lagavulin', act: 1, type: 'elite', hp_min: 109, hp_max: 109, intents: '[{"pattern":"睡眠","damage":0,"condition":"前两回合"},{"pattern":"攻击+debuff","damage":18,"buff":"-1力量-1敏捷"}]', strategy_general: '前2回合睡眠，可以铺垫。醒来后每2回合攻击一次，伤害很高。', strategy_by_character: '{"ironclad":"提前叠力量","silent":"铺垫毒","defect":"铺垫充能球","watcher":"铺垫姿态牌"}' },
  { game_version: 'sts1', name_cn: '真菌兽', name_en: 'Fungi Beast', act: 1, type: 'elite', hp_min: 64, hp_max: 64, intents: '[{"pattern":"攻击","damage":6},{"pattern":"强化+攻击","damage":8,"buff":"力量+3"}]', strategy_general: '两只一组。优先击杀一只，防止被狂暴。死后给予易伤。', strategy_by_character: '{"ironclad":"AOE或逐个击杀","silent":"双目标毒很赚","defect":"闪电球打两个","watcher":"AOE能力"}' },
  // Act 1 BOSS
  { game_version: 'sts1', name_cn: '史莱姆老大', name_en: 'Slime Boss', act: 1, type: 'boss', hp_min: 140, hp_max: 140, intents: '[{"pattern":"攻击","damage":35,"condition":"第1,4,7...回合"},{"pattern":"强化","buff":"分裂","condition":"血量≤50%"}]', strategy_general: '血量≤50%时会分裂成2个中史莱姆。尽量在它分裂前一波爆发压低血量，然后AOE处理分裂体。', strategy_by_character: '{"ironclad":"重刃/突破极限爆发","silent":"毒对分裂体持续","defect":"电动力学AOE","watcher":"愤怒姿态爆发"}' },
  { game_version: 'sts1', name_cn: '守护者', name_en: 'The Guardian', act: 1, type: 'boss', hp_min: 240, hp_max: 240, intents: '[{"pattern":"攻击","damage":32,"condition":"普通形态"},{"pattern":"尖刺防御","block":20,"buff":"反击尖刺","condition":"防御形态"}]', strategy_general: '防御形态下受攻击会反击。攻击形态下输出很高。建议在攻击形态爆发，防御形态用格挡/毒/充能球。', strategy_by_character: '{"ironclad":"防御形态避免攻击，攻击形态爆发","silent":"毒是最好的解法","defect":"充能球避开尖刺","watcher":"平静姿态格挡"}' },
  { game_version: 'sts1', name_cn: '六火亡魂', name_en: 'Hexaghost', act: 1, type: 'boss', hp_min: 250, hp_max: 250, intents: '[{"pattern":"蓄力","damage":0,"condition":"第1,4回合"},{"pattern":"攻击","damage":6,"condition":"第2,3,5,6回合x6次"}]', strategy_general: '第1回合蓄力（不攻击），第2-3回合6x6伤害。第4回合再次蓄力。利用蓄力回合铺垫。', strategy_by_character: '{"ironclad":"火焰屏障很赚","silent":"毒持续输出","defect":"冰霜球堆格挡","watcher":"格挡+反击"}' },
  // Act 2 普通
  { game_version: 'sts1', name_cn: '蛇花', name_en: 'Spheric Guardian', act: 2, type: 'normal', hp_min: 40, hp_max: 44, intents: '[{"pattern":"攻击+脆弱","damage":10,"buff":"脆弱"}]', strategy_general: '会给脆弱，尽早击杀。', strategy_by_character: null },
  { game_version: 'sts1', name_cn: '百夫长', name_en: 'Centurion', act: 2, type: 'normal', hp_min: 60, hp_max: 60, intents: '[{"pattern":"攻击","damage":12},{"pattern":"治疗","buff":"治疗15"}]', strategy_general: '百夫长会治疗，优先击杀。', strategy_by_character: null },
  // Act 2 精英
  { game_version: 'sts1', name_cn: '.book of stabbing', name_en: 'Book of Stabbing', act: 2, type: 'elite', hp_min: 160, hp_max: 168, intents: '[{"pattern":"多段攻击","damage":6,"condition":"x(6+受伤次数)"}]', strategy_general: '攻击次数随受伤增加而增加。需要高格挡或快速击杀。', strategy_by_character: '{"ironclad":"高格挡应对","silent":"毒是最优解","defect":"冰霜球堆格挡","watcher":"愤怒爆发或平静格挡"}' },
  { game_version: 'sts1', name_cn: 'shelled parasite', name_en: 'Shelled Parasite', act: 2, type: 'elite', hp_min: 68, hp_max: 68, intents: '[{"pattern":"攻击+吸血","damage":18,"buff":"吸血"}]', strategy_general: '有外壳保护，吸血攻击。需要破甲后快速击杀。', strategy_by_character: null },
  // Act 2 BOSS
  { game_version: 'sts1', name_cn: '青铜自动机', name_en: 'Bronze Automaton', act: 2, type: 'boss', hp_min: 300, hp_max: 300, intents: '[{"pattern":"攻击","damage":45},{"pattern":"召唤","buff":"召唤铜球"},{"pattern":"强化","buff":"重生"}]', strategy_general: '会召唤铜球（必须优先击杀，否则造成大量伤害）。死后会重生一次。', strategy_by_character: '{"ironclad":"优先铜球","silent":"AOE毒","defect":"闪电球处理铜球","watcher":"愤怒爆发"}' },
  { game_version: 'sts1', name_cn: '冠军', name_en: 'The Champ', act: 2, type: 'boss', hp_min: 420, hp_max: 420, intents: '[{"pattern":"攻击","damage":12},{"pattern":"重击","damage":30,"condition":"半血以下"}]', strategy_general: '半血以下进入狂暴，伤害大幅提升。尽量在半血前准备好爆发或格挡。', strategy_by_character: '{"ironclad":"半血前爆发","silent":"提前叠毒","defect":"铺垫后一波","watcher":"姿态切换爆发"}' },
  { game_version: 'sts1', name_cn: '收藏家', name_en: 'The Collector', act: 2, type: 'boss', hp_min: 280, hp_max: 280, intents: '[{"pattern":"攻击","damage":18},{"pattern":"召唤","buff":"召唤火炬头"}]', strategy_general: '会召唤火炬头，需要处理小怪。', strategy_by_character: null },
  // Act 3
  { game_version: 'sts1', name_cn: '觉醒者', name_en: 'Awakened One', act: 3, type: 'boss', hp_min: 300, hp_max: 300, intents: '[{"pattern":"攻击","damage":20},{"pattern":"强化","buff":"力量+2"}]', strategy_general: '会使用能力牌叠加力量。尽量不要出太多能力牌。第二阶段伤害很高。', strategy_by_character: '{"ironclad":"少出能力牌，爆发击杀","silent":"毒不受影响","defect":"少出能力牌","watcher":"正常输出"}' },
  { game_version: 'sts1', name_cn: '甜圈八', name_en: 'Donu and Deca', act: 3, type: 'boss', hp_min: 250, hp_max: 250, intents: '[{"pattern":"攻击","damage":10},{"pattern":"强化","buff":"格挡+力量"}]', strategy_general: '两个目标，互相强化。优先击杀其中一个。', strategy_by_character: '{"ironclad":"AOE或集火","silent":"双目标毒很赚","defect":"闪电球AOE","watcher":"AOE姿态"}' },
  { game_version: 'sts1', name_cn: '时间吞噬者', name_en: 'Time Eater', act: 3, type: 'boss', hp_min: 450, hp_max: 450, intents: '[{"pattern":"攻击","damage":26},{"pattern":"时间扭曲","buff":"恢复格挡"}]', strategy_general: '每打出12张牌会强制结束回合。控制出牌数量，不要过牌太多。', strategy_by_character: '{"ironclad":"控制出牌数","silent":"毒是最好的解法","defect":"不要过牌太多","watcher":"控制姿态切换次数"}' },
  // Act 4
  { game_version: 'sts1', name_cn: '腐化之心', name_en: 'Corrupt Heart', act: 4, type: 'boss', hp_min: 750, hp_max: 750, intents: '[{"pattern":"攻击","damage":40},{"pattern":"debuff","buff":"能力反转"}]', strategy_general: '最终BOSS。需要高爆发和生存能力。准备好药水。', strategy_by_character: '{"ironclad":"高爆发卡组","silent":"高毒卡组","defect":"高充能球输出","watcher":"姿态爆发"}' },
  // StS2 Early Access (部分已知)
  { game_version: 'sts2', name_cn: '腐化蠕虫', name_en: 'Corrupt Worm', act: 1, type: 'normal', hp_min: 30, hp_max: 35, intents: '[{"pattern":"攻击","damage":8},{"pattern":"毒液","buff":"中毒3层"}]', strategy_general: '会施加中毒，注意血量管理。', strategy_by_character: null },
  { game_version: 'sts2', name_cn: '暗影守卫', name_en: 'Shadow Warden', act: 2, type: 'elite', hp_min: 120, hp_max: 120, intents: '[{"pattern":"攻击","damage":15},{"pattern":"隐身","buff":"下回合攻击翻倍"}]', strategy_general: '隐身回合会蓄力，下回合高伤害。做好格挡。', strategy_by_character: null },
];
